apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conduit-data
  namespace: conduit
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 20Gi
